module.exports = {
  vegetables: [
    "Tomato",
    "Onion",
    "Garlic",
    "Bell Pepper",
    "Carrot",
    "Potato",
    "Broccoli",
    "Spinach",
    "Kale",
    "Zucchini",
    "Cucumber",
    "Lettuce",
    "Mushrooms",
    "Eggplant",
    "Green Beans",
    "Cauliflower",
    "Celery",
    "Corn",
    "Sweet Potato",
    "Squash",
    "Avocado",
  ],
  fruits: [
    "Apple",
    "Banana",
    "Orange",
    "Lemon",
    "Lime",
    "Strawberry",
    "Blueberry",
    "Raspberry",
    "Mango",
    "Pineapple",
    "Watermelon",
    "Peach",
    "Pear",
    "Grapes",
    "Pomegranate",
    "Kiwi",
    "Cherry",
    "Papaya",
    "Coconut",
  ],
  meat: [
    "Chicken Breast",
    "Chicken Thinghs",
    "Ground Beef",
    "Beef Steak",
    "Pork Chops",
    "Ground Pork",
    "Bacon",
    "Lamb",
    "Turkey",
    "Duck",
  ],
  fish: [
    "Salmon",
    "Tuna",
    "Shrimp",
    "Cod",
    "Scallops",
    "Crab",
    "Lobster",
    "Mussels",
    "Tilapia",
    "Sardines",
  ],
  dairy: [
    "Milk",
    "Cream",
    "Butter",
    "Yogurt",
    "Cheese",
    "Sour Cream",
    "Cottage Cheese",
    "Cream Cheese",
  ],
  grain: [
    "Rice",
    "Quinoa",
    "Couscous",
    "Barley",
    "Oats",
    "Spaghetti",
    "Lasagna Noodles",
    "Fettuccine",
    "Bulgur Wheat",
  ],
  legumes: [
    "Lentils",
    "Chickpeas",
    "Black beans",
    "Pinto Beans",
    "Green Peas",
    "Split Peas",
  ],
  herbs: [
    "Basil",
    "Oregano",
    "Thyme",
    "Rosemary",
    "Parsley",
    "Cilantro",
    "Dill",
    "Mint",
    "Paprika",
    "Cumin",
    "Turmeric",
    "Cinnamon",
    "Nutmeg",
    "Ginger",
    "Black Pepper",
    "Red Pepper Flakes",
    "Cayenne Pepper",
    "Bay Leaves",
  ],
  baking: [
    "Flour",
    "Sugar",
    "Baking Powder",
    "Baking Soda",
    "Yeast",
    "Cocoa Powder",
    "Cornstarch",
    "Vanilla Extract",
    "Oil",
    "Olive Oil",
    "Vegetable Oil",
    "Vinegar",
    "Honey",
    "Maple Syrup",
    "Salt",
    "Egg",
  ],
  nuts: [
    "Almonds",
    "Walnuts",
    "Cashews",
    "Pecans",
    "Peanuts",
    "Sunflower Seeds",
    "Pumpkin Seeds",
    "Chia Seeds",
    "Flaxseeds",
  ],
  sauces: [
    "Ketchup",
    "Mustard",
    "Mayonnaise",
    "Barbecue Sauce",
    "Hot Sauce",
    "Soy Sauce",
    "Worcestershire Sauce",
    "Tahini",
    "Salsa",
    "Peanut Butter",
  ],
  pantry: [
    "Cannnes Tomatoes",
    "Tomato Paste",
    "Tomato Sauce",
    "Cocunt Milk",
    "Chicken Broth",
    "Canned Tuna",
    "Beef Broth",
    "Pasta Sauce",
    "Pickles",
    "Olives",
    "Capers",
  ],
  beverages: ["Coffee", "Tea", "Orange Juice", "Apple Juice", "Coconut Water"],
  frozen: [
    "Frozen Peas",
    "Frozen Mixed Vegetables",
    "Frozen Berrirs",
    "Frozen Spinach",
    "Ice Cream",
    "Frozen Pizza Dough",
  ],
};
